[build]
  command = "cd backend && npm install"
  functions = "backend"
  publish = "frontend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd backend && npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"
